### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by gmelnik** [vikas-sanap/openstack-addon-for-splunk#1]
Vikas, the contact email listed with the OpenStack App and AddOn for Splunk on Splunkbase seems to be bouncing. You've requested app certification and we have completed the check of pre-requisites. Please update your contact info on Splunkbase so that we could send you the report.

Grigori
Splunk App Cert Admin

**Comment by vikas-sanap** [comment]
Sorry for this issue.
Now contact email is working.
Thanks,
Vikas
